### ISSUE TITLE
webpack-dev-server fails when using Webpack

### ISSUE THREAD

**Issue by nommuna2** [Esri/jsapi-resources#129]
I am reporting an issue with 
- [x] another resource in this repository

Running the webpack configuration listed here: https://github.com/Esri/jsapi-resources/tree/master/4.x/webpack.

After cloning the repro and npm installing the files. I run the command npm start and get the folllowing error.....

> PS C:\Users\user\Desktop\Webpack\webpack\demo> npm start

> arcgis-webpack-plugin-sample@0.0.1 start C:\Users\user\Desktop\Webpack\webpack\demo
> webpack-dev-server --mode development --open

>C:\Users\user\Desktop\Webpack\webpack\demo\node_modules\@arcgis\webpack-plugin\index.js:90
    this.options = { ...this.options, ...options.options };
                     ^^^
SyntaxError: Unexpected token ...
    at Object.exports.runInThisContext (vm.js:76:16)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Users\user\Desktop\Webpack\webpack\demo\webpack.config.js:1:84)
    at Module._compile (module.js:570:32)

>npm ERR! Windows_NT 10.0.16299
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
npm ERR! node v6.9.5
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! arcgis-webpack-plugin-sample@0.0.1 start: `webpack-dev-server --mode development --open`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the arcgis-webpack-plugin-sample@0.0.1 start script 'webpack-dev-server --mode development --open'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the arcgis-webpack-plugin-sample package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     webpack-dev-server --mode development --open
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs arcgis-webpack-plugin-sample
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls arcgis-webpack-plugin-sample
npm ERR! There is likely additional logging output above.

>npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\user\Desktop\Webpack\webpack\demo\npm-debug.log

Seems to fail when running 
> webpack-dev-server --mode development --open

System Settings: 
Windows 10, Node version 6.9.5.

Attached is the npm-debug log.
[npm-debug.log](https://github.com/Esri/jsapi-resources/files/1956251/npm-debug.log)

Any ideas on what I am doing wrong?

**Comment by nommuna2** [comment]
@lheberlie Thanks! That seemed to do the trick.
