### ISSUE TITLE
4.x webpack demo build error on Windows 10

### ISSUE THREAD

**Issue by ramunask** [Esri/jsapi-resources#131]
`npm run build` fails for `4.x\webpack\demo` on Windows 10 machine. See logs:
```
C:\temp\jsapi-resources\4.x\webpack\demo>npm install
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.1.2 (node_modules\chokidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN arcgis-webpack-plugin-sample@0.0.1 No repository field.

C:\temp\jsapi-resources\4.x\webpack\demo>npm run build

> arcgis-webpack-plugin-sample@0.0.1 build C:\temp\jsapi-resources\4.x\webpack\demo
> webpack --mode production

C:\temp\jsapi-resources\4.x\webpack\demo\node_modules\@arcgis\webpack-plugin\index.js:90
    this.options = { ...this.options, ...options.options };
                     ^^^
SyntaxError: Unexpected token ...
    at NativeCompileCache._moduleCompile (C:\temp\jsapi-resources\4.x\webpack\demo\node_modules\v8-compile-cache\v8-compile-cache.js:226:18)
    at Module._compile (C:\temp\jsapi-resources\4.x\webpack\demo\node_modules\v8-compile-cache\v8-compile-cache.js:172:36)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (C:\temp\jsapi-resources\4.x\webpack\demo\node_modules\v8-compile-cache\v8-compile-cache.js:159:20)
    at Object.<anonymous> (C:\temp\jsapi-resources\4.x\webpack\demo\webpack.config.js:1:84)
    at Module._compile (C:\temp\jsapi-resources\4.x\webpack\demo\node_modules\v8-compile-cache\v8-compile-cache.js:178:30)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (C:\temp\jsapi-resources\4.x\webpack\demo\node_modules\v8-compile-cache\v8-compile-cache.js:159:20)
    at WEBPACK_OPTIONS (C:\temp\jsapi-resources\4.x\webpack\demo\node_modules\webpack-cli\bin\convert-argv.js:133:13)
    at requireConfig (C:\temp\jsapi-resources\4.x\webpack\demo\node_modules\webpack-cli\bin\convert-argv.js:135:6)
    at C:\temp\jsapi-resources\4.x\webpack\demo\node_modules\webpack-cli\bin\convert-argv.js:142:17
    at Array.forEach (native)
    at module.exports (C:\temp\jsapi-resources\4.x\webpack\demo\node_modules\webpack-cli\bin\convert-argv.js:140:15)
    at yargs.parse.err (C:\temp\jsapi-resources\4.x\webpack\demo\node_modules\webpack-cli\bin\webpack.js:239:39)
    at Object.parse (C:\temp\jsapi-resources\4.x\webpack\demo\node_modules\webpack-cli\node_modules\yargs\yargs.js:552:18)
    at C:\temp\jsapi-resources\4.x\webpack\demo\node_modules\webpack-cli\bin\webpack.js:217:8
    at Object.<anonymous> (C:\temp\jsapi-resources\4.x\webpack\demo\node_modules\webpack-cli\bin\webpack.js:514:3)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)

npm ERR! Windows_NT 10.0.17134
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "build"
npm ERR! node v6.9.1
npm ERR! npm  v3.10.8
npm ERR! code ELIFECYCLE
npm ERR! arcgis-webpack-plugin-sample@0.0.1 build: `webpack --mode production`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the arcgis-webpack-plugin-sample@0.0.1 build script 'webpack --mode production'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the arcgis-webpack-plugin-sample package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     webpack --mode production
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs arcgis-webpack-plugin-sample
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls arcgis-webpack-plugin-sample
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\temp\jsapi-resources\4.x\webpack\demo\npm-debug.log

C:\temp\jsapi-resources\4.x\webpack\demo>
```

**Comment by lheberlie** [comment]
Hi @ramunask,

Can you verify that you're not having the same issue as described in https://github.com/Esri/jsapi-resources/issues/129#issuecomment-385467551 about the [arcgis-webpack-plugin](https://github.com/Esri/arcgis-webpack-plugin/blob/master/package.json#L7) also recommends `>=8.9.3`.?

Lloyd

**Comment by ramunask** [comment]
Yes. Upgrading `nodejs` to version `v10.0.0` helped

**Comment by FaroukMohameden** [comment]
I have this issue with both v10 (Recommanded for most users) and v11 (Latest features). Does this mean that it requires a specific version of Node ?
