### ISSUE TITLE
JavaScript API 4.17  Editor widget 

### ISSUE THREAD

**Issue by yangyachao** [Esri/jsapi-resources#223]
When I update a feature layer,there is an error：
`TypeError: Cannot read property 'length' of undefined
    at Function.d.fromOptimizedFeatureSet (https://js.arcgis.com/4.17/esri/views/2d/layers/features/Pipeline.js:1153:197)
    at Function.d.fromFeatureSet (https://js.arcgis.com/4.17/esri/views/2d/layers/features/Pipeline.js:1152:492)
    at c.<anonymous> (https://js.arcgis.com/4.17/esri/views/2d/layers/features/Pipeline.js:979:91)
    at d (https://js.arcgis.com/4.17/dojo/dojo-lite.js:47:190)
    at Object.next (https://js.arcgis.com/4.17/dojo/dojo-lite.js:45:492)
    at g (https://js.arcgis.com/4.17/dojo/dojo-lite.js:45:275)`
<img width="703" alt="image" src="https://user-images.githubusercontent.com/4145688/96406634-72d1de80-1212-11eb-96e3-76f476a8d1e4.png">

<img width="833" alt="image" src="https://user-images.githubusercontent.com/4145688/96406480-179fec00-1212-11eb-9e67-3a4da2452c89.png">
<img width="1038" alt="image" src="https://user-images.githubusercontent.com/4145688/96406573-47e78a80-1212-11eb-9237-ab46eb2e5254.png">

**but it works normally in version 4.16**

**Comment by hgonzago** [comment]
Could you retry this again using 4.17? We patched this. It had to deal with services that didn't support the pbf format.

**Comment by yangyachao** [comment]
@hgonzago I retry this, It's works in 4.17;  Thanks very much for your help! 😃

**Comment by yangyachao** [comment]
@hgonzago When will the offline version be updated?

**Comment by hgonzago** [comment]
We are planning on hopefully getting this out next week.

@yangyachao
