### ISSUE TITLE
4.x Demo - UnhandledPromiseRejectionWarning: ServeCommand cannot be invoked without 'new'

### ISSUE THREAD

**Issue by elake2018** [Esri/jsapi-resources#250]
Clone Project
open Demo Folder
run npm i
run npm run-script start

(node:32784) UnhandledPromiseRejectionWarning: TypeError: Class constructor ServeCommand cannot be invoked without 'new'
    at run (C:\ESRI-JS-API_4-18\jsapi-resources\4.x\webpack\demo\node_modules\webpack-cli\lib\utils\resolve-command.js:33:12)
    at Command.<anonymous> (C:\ESRI-JS-API_4-18\jsapi-resources\4.x\webpack\demo\node_modules\webpack-cli\lib\utils\arg-parser.js:34:58)
    at Command.listener [as _actionHandler] (C:\ESRI-JS-API_4-18\jsapi-resources\4.x\webpack\demo\node_modules\webpack-cli\node_modules\commander\index.js:426:31)
    at Command._parseCommand (C:\ESRI-JS-API_4-18\jsapi-resources\4.x\webpack\demo\node_modules\webpack-cli\node_modules\commander\index.js:1002:14)
    at Command._dispatchSubcommand (C:\ESRI-JS-API_4-18\jsapi-resources\4.x\webpack\demo\node_modules\webpack-cli\node_modules\commander\index.js:953:18)
    at Command._parseCommand (C:\ESRI-JS-API_4-18\jsapi-resources\4.x\webpack\demo\node_modules\webpack-cli\node_modules\commander\index.js:970:12)
    at Command.parse (C:\ESRI-JS-API_4-18\jsapi-resources\4.x\webpack\demo\node_modules\webpack-cli\node_modules\commander\index.js:801:10)
    at argParser (C:\ESRI-JS-API_4-18\jsapi-resources\4.x\webpack\demo\node_modules\webpack-cli\lib\utils\arg-parser.js:164:27)
    at runCLI (C:\ESRI-JS-API_4-18\jsapi-resources\4.x\webpack\demo\node_modules\webpack-cli\lib\bootstrap.js:11:24)
    at Object.<anonymous> (C:\ESRI-JS-API_4-18\jsapi-resources\4.x\webpack\demo\node_modules\webpack-cli\bin\cli.js:24:5)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:32784) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:32784) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

I am reporting an issue with 

- [ ] TypeScript definitions
- [ ] another resource in this repository

**Comment by odoe** [comment]
I'm not seeing this error. Can you provide your node/npm version as well.

I notice you're on windows, maybe try installing the [windows build tools](https://github.com/felixrieseberg/windows-build-tools), not sure if that will help.

**Comment by elake2018** [comment]
I am using Node v.12.13.1
And npm 6.12.1

I have been developing on this machine using node/npm/react for some time, so I have the build tools installed, this may require a different version, not sure.

**Comment by odoe** [comment]
Looks like it was the version of webpack-cli that needed to be updated. Not sure why the error didn't pop up on other machines. Should be fixed now.

**Comment by XPLing** [comment]
> Looks like it was the version of webpack-cli that needed to be updated. Not sure why the error didn't pop up on other machines. Should be fixed now.

I use @arcgis/core in my Vue project and I also encountered the same problem
```

// version info:
vue@2.5.17
@arcgis/core@4.19.3
webpack@4.41.5
node@v10.20.0
npm@6.14.4
```

I found that I will have this error when I extend any class
eg:
```
class demo extends Graphic{
      constructor () {super();}
    }
```

I will get the error that "Class constructor p cannot be invoked without 'new'", I don't know how to solve this error

Can you provide the version of the webpack?

**Comment by odoe** [comment]
@XPLing that is an unrelated error. Most likely you need to update your version of webpack to v5. The node version is very old as well, latest LTS is v14. You might need to upgrade just about everything.
