### ISSUE TITLE
HistogramTimeSlider - bug?

### ISSUE THREAD

**Issue by RolandVanZoest** [Esri/jsapi-resources#27]
Hello all,

I'm quite fresh in JS and the ESRI API and I hope this is the right spot ...

While customizing the HistogramTimeSlider sample code ( https://developers.arcgis.com/javascript/3/jssamples/widget_histogram_time_slider.html )
I experienced a possible bug in this widget.

Have a look at this url/script : 
http://www.geo-informatie.nl/zoest001/AGO-JS/TimeSliderHistogram/HistogramTimeSlider-Months.html
The polygons are time-grouped by months, which is to coarse.
Grouping by days works fine too, but is to detailed.
Grouping them by weeks ( timeInterval: "esriTimeUnitsMonths" ) :
http://www.geo-informatie.nl/zoest001/AGO-JS/TimeSliderHistogram/HistogramTimeSlider-Weeks.html
leads to an error (InternetExplorer-11 and Chrome-51) :
`
TypeError: Unable to draw graphic (null): Unable to get property 'length' of undefined or null reference TypeError: Unable to draw graphic (null): Unable to get property 'length' of undefined or null reference
   at _add (http://js.arcgis.com/3.17/esri/dijit/HistogramTimeSlider.js:18:458)
   at Anonymous function (http://js.arcgis.com/3.17/esri/dijit/HistogramTimeSlider.js:9:195)
   at Anonymous function (http://js.arcgis.com/3.17/:644:363)
   at c (http://js.arcgis.com/3.17/:119:64)
   at _fireUpdateEnd (http://js.arcgis.com/3.17/:848:341)
   at _applyTimeFilter (http://js.arcgis.com/3.17/:1992:415)
   at propertyChangeHandler (http://js.arcgis.com/3.17/:1984:196)
   at _timeChangeHandler (http://js.arcgis.com/3.17/:1928:19)
   at Anonymous function (http://js.arcgis.com/3.17/:63:200)
   at c (http://js.arcgis.com/3.17/:119:64)
   {
      [functions]: ,
      __proto__: { },
      description: "Unable to get property 'length' of undefined or null reference",
      message: "Unable to draw graphic (null): Unable to get property 'length' of undefined or null reference",
      name: "TypeError",
      number: -2146823281,
      stack: "TypeError: Unable to draw graphic (null): Unable to get property 'length' of undefined or null reference
   at _add (http://js.arcgis.com/3.17/esri/dijit/HistogramTimeSlider.js:18:458)
   at Anonymous function (http://js.arcgis.com/3.17/esri/dijit/HistogramTimeSlider.js:9:195)
   at Anonymous function (http://js.arcgis.com/3.17/:644:363)
   at c (http://js.arcgis.com/3.17/:119:64)
   at _fireUpdateEnd (http://js.arcgis.com/3.17/:848:341)
   at _applyTimeFilter (http://js.arcgis.com/3.17/:1992:415)
   at propertyChangeHandler (http://js.arcgis.com/3.17/:1984:196)
   at _timeChangeHandler (http://js.arcgis.com/3.17/:1928:19)
   at Anonymous function (http://js.arcgis.com/3.17/:63:200)
   at c (http://js.arcgis.com/3.17/:119:64)"
   }
   "TypeError: Unable to draw graphic (null): Unable to get property 'length' of undefined or null reference
   at _add (http://js.arcgis.com/3.17/esri/dijit/HistogramTimeSlider.js:18:458)
   at Anonymous function (http://js.arcgis.com/3.17/esri/dijit/HistogramTimeSlider.js:9:195)
   at Anonymous function (http://js.arcgis.com/3.17/:644:363)
   at c (http://js.arcgis.com/3.17/:119:64)
   at _fireUpdateEnd (http://js.arcgis.com/3.17/:848:341)
   at _applyTimeFilter (http://js.arcgis.com/3.17/:1992:415)
   at propertyChangeHandler (http://js.arcgis.com/3.17/:1984:196)
   at _timeChangeHandler (http://js.arcgis.com/3.17/:1928:19)
   at Anonymous function (http://js.arcgis.com/3.17/:63:200)
   at c (http://js.arcgis.com/3.17/:119:64)"
`

Kind regards,
Roland van Zoest (NL)

**Comment by RolandVanZoest** [comment]
Oops ... in the previous text
    timeInterval: "esriTimeUnitsMonths"
should be
    timeInterval: "esriTimeUnitsWeeks"

**Comment by bsvensson** [comment]
This is a "Week" bug in the HistogramTimeSlider of the ArcGIS API for JavaScript. Other time units seems to work fine.

Thanks for reporting. (Sorry for slow response)

The issue you mention above isn't specific to anything in this repo. The preferred way to report bugs with the ArcGIS API for JavaScript is using [Esri Support](https://support.esri.com/contact-tech-support).

However, if you find issues related to this repo (bower, sass, typescript, jshint, oauth), then you can also raise them as issues in this repo.  See also https://github.com/Esri/jsapi-resources/blob/master/CONTRIBUTING.md for more information.

Again, thanks for reporting the bug.

**Comment by RolandVanZoest** [comment]
Thanks  Bjorn,

 

So it’s a real bug … good to know now.

It hasn’t kept me sleepless for last year ;-)

 

“Esri Support” isn’t very easy to contact/use from outside the USA … L

 

Thanks again,

Roland @ GeoDesk

 

 

Van: Bjorn Svensson [mailto:notifications@github.com] 
Verzonden: vrijdag 27 oktober 2017 00:54
Aan: Esri/jsapi-resources
CC: RolandVanZoest; Author
Onderwerp: Re: [Esri/jsapi-resources] HistogramTimeSlider - bug? (#27)

 

This is a "Week" bug in the HistogramTimeSlider of the ArcGIS API for JavaScript. Other time units seems to work fine.

Thanks for reporting. (Sorry for slow response)

The issue you mention above isn't specific to anything in this repo. The preferred way to report bugs with the ArcGIS API for JavaScript is using Esri Support <https://support.esri.com/contact-tech-support> .

However, if you find issues related to this repo (bower, sass, typescript, jshint, oauth), then you can also raise them as issues in this repo. See also https://github.com/Esri/jsapi-resources/blob/master/CONTRIBUTING.md for more information.

Again, thanks for reporting the bug.
