### ISSUE TITLE
2 esm samples currently not working

### ISSUE THREAD

**Issue by opike** [Esri/jsapi-resources#487]
### IMPORTANT

- [X] My question is related to the samples and content within this repository. For all other issues, open a ticket with [Esri Technical Support](https://support.esri.com/) or post your question in the [community forum](https://community.esri.com/t5/arcgis-api-for-javascript/ct-p/arcgis-api-for-javascript).
- [X] I have [checked for existing issues](https://github.com/Esri/jsapi-resources/issues) to avoid duplicates. If someone has already opened an issue for what you are experiencing, please add a 👍 reaction and comment as necessary to the existing issue instead of creating a new one. You can also refer to this repo's [troubleshooting guide](../../TROUBLESHOOTING.md) for hints and suggestions.

### Actual behavior

I'm able to run the sample esm-samples/jsapi-node/test-projection.js successfully, but the other two samples in the same directory, test-request.js and test-webmap.js, fail with error messages. 

test-webmap.js:
```
[esri.WebMap] #load() Failed to load web map s {
  name: 'webmap:load-portal-item',
  details: {
    error: TypeError: Cannot read properties of undefined (reading 'bind')
        at $ (/Volumes/github-image/esri/jsapi-resources/esm-samples/jsapi-node/public/chunks/request.js:133:2347)
        at Object.j$1 [as j] (/Volumes/github-image/esri/jsapi-resources/esm-samples/jsapi-node/public/chunks/request.js:133:878)
        at p.request (/Volumes/github-image/esri/jsapi-resources/esm-samples/jsapi-node/public/webmap.js:112:7521)
        at p.fetchSelf (/Volumes/github-image/esri/jsapi-resources/esm-samples/jsapi-node/public/webmap.js:112:5682)
        at /Volumes/github-image/esri/jsapi-resources/esm-samples/jsapi-node/public/webmap.js:112:3433
        at async Promise.all (index 2)
  },
  message: 'Failed to load portal item'
}
s {
  name: 'webmap:load-portal-item',
  details: {
    error: TypeError: Cannot read properties of undefined (reading 'bind')
        at $ (/Volumes/github-image/esri/jsapi-resources/esm-samples/jsapi-node/public/chunks/request.js:133:2347)
        at Object.j$1 [as j] (/Volumes/github-image/esri/jsapi-resources/esm-samples/jsapi-node/public/chunks/request.js:133:878)
        at p.request (/Volumes/github-image/esri/jsapi-resources/esm-samples/jsapi-node/public/webmap.js:112:7521)
        at p.fetchSelf (/Volumes/github-image/esri/jsapi-resources/esm-samples/jsapi-node/public/webmap.js:112:5682)
        at /Volumes/github-image/esri/jsapi-resources/esm-samples/jsapi-node/public/webmap.js:112:3433
        at async Promise.all (index 2)
  },
  message: 'Failed to load portal item'
}
``` 

test-request.js:
```
TypeError: Cannot read properties of undefined (reading 'bind')
    at $ (/Volumes/github-image/esri/jsapi-resources/esm-samples/jsapi-node/public/chunks/request.js:133:2347)
    at Object.j$1 [as j] (/Volumes/github-image/esri/jsapi-resources/esm-samples/jsapi-node/public/chunks/request.js:133:878)
    at Object.<anonymous> (/Volumes/github-image/esri/jsapi-resources/esm-samples/jsapi-node/public/request.js:9:9)
    at Module._compile (node:internal/modules/cjs/loader:1126:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1180:10)
    at Module.load (node:internal/modules/cjs/loader:1004:32)
    at Function.Module._load (node:internal/modules/cjs/loader:839:12)
    at Module.require (node:internal/modules/cjs/loader:1028:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/Volumes/github-image/esri/jsapi-resources/esm-samples/jsapi-node/test-request.js:3:1)
```

### Expected behavior

That the samples would run without an error (presumably they will return some metadata from arcGIS online).

### Reproduction sample

https://github.com/Esri/jsapi-resources/blob/main/esm-samples/jsapi-node/test-webmap.js

### Reproduction steps

npm install
npm run build
node test-webmap.js

### Reproduction browser

Chrome 116.0.5845.187

### Operating System (check https://whatsmyos.com)

Mac OS Ventura 13.5, Apple Silicon
Node 16.17.1

**Comment by opike** [comment]
@andygup Thanks for the suggestion. I ended up trying it on a Macbook with intel silicon using Node 20 and that worked. I'm not sure yet if it was the node version or the processor that fixed the problem. From your message it sounds like it was probably the node version.
